# Generated by Django 3.1.12 on 2024-11-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_auto_20241120_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='study',
            name='phase',
            field=models.CharField(choices=[('Phase I', 'Phase I'), ('Phase II', 'Phase II'), ('Phase III', 'Phase III'), ('Phase IV', 'Phase IV')], max_length=20),
        ),
        migrations.AlterField(
            model_name='study',
            name='sponsor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='study',
            table='studies_study',
        ),
    ]
